#!/usr/bin/env python
"""
Copyright 2011 Wordnik, Inc.
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class WordListWordsInput:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'wordListId': 'str',
            'sortBy': 'str',
            'sortOrder': 'str',
            'skip': 'str',
            'limit': 'str',
            'auth_token': 'str'
        }



        # ID of WordList to use
        self.wordListId = None # str


        # Field to sort by
        self.sortBy = None # str


        # Direction to sort
        self.sortOrder = None # str


        # Results to skip
        self.skip = None # str


        # Maximum number of results to return
        self.limit = None # str


        # The auth token of the logged-in user, obtained by calling /account.{format}/authenticate/{username} (described above)
        self.auth_token = None # str

