#!/usr/bin/env python
"""
Copyright 2011 Wordnik, Inc.
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class WordExamplesInput:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'word': 'str',
            'includeDuplicates': 'str',
            'contentProvider': 'str',
            'useCanonical': 'str',
            'skip': 'str',
            'limit': 'str'
        }



        # Word to return examples for
        self.word = None # str


        # Show duplicate examples from different sources
        self.includeDuplicates = None # str


        # Return results from a specific ContentProvider
        self.contentProvider = None # str


        # If true will try to return the correct word root ('cats' -> 'cat'). If false returns exactly what was requested.
        self.useCanonical = None # str


        # Results to skip
        self.skip = None # str


        # Maximum number of results to return
        self.limit = None # str

