#!/usr/bin/env python
"""
Copyright 2011 Wordnik, Inc.
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class WordsRandomWordInput:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'hasDictionaryDef': 'str',
            'includePartOfSpeech': 'str',
            'excludePartOfSpeech': 'str',
            'minCorpusCount': 'str',
            'maxCorpusCount': 'str',
            'minDictionaryCount': 'str',
            'maxDictionaryCount': 'str',
            'minLength': 'str',
            'maxLength': 'str'
        }



        # Only return words with dictionary definitions
        self.hasDictionaryDef = None # str


        # CSV part-of-speech values to include
        self.includePartOfSpeech = None # str


        # CSV part-of-speech values to exclude
        self.excludePartOfSpeech = None # str


        # Minimum corpus frequency for terms
        self.minCorpusCount = None # str


        # Maximum corpus frequency for terms
        self.maxCorpusCount = None # str


        # Minimum dictionary count
        self.minDictionaryCount = None # str


        # Maximum dictionary count
        self.maxDictionaryCount = None # str


        # Minimum word length
        self.minLength = None # str


        # Maximum word length
        self.maxLength = None # str

