#!/usr/bin/env python
"""
Copyright 2011 Wordnik, Inc.
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class WordsRandomWordsInput:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'hasDictionaryDef': 'str',
            'includePartOfSpeech': 'str',
            'excludePartOfSpeech': 'str',
            'minCorpusCount': 'str',
            'maxCorpusCount': 'str',
            'minDictionaryCount': 'str',
            'maxDictionaryCount': 'str',
            'minLength': 'str',
            'maxLength': 'str',
            'sortBy': 'str',
            'sortOrder': 'str',
            'limit': 'str'
        }



        # Only return words with dictionary definitions
        self.hasDictionaryDef = None # str


        # CSV part-of-speech values to include
        self.includePartOfSpeech = None # str


        # CSV part-of-speech values to exclude
        self.excludePartOfSpeech = None # str


        # Minimum corpus frequency for terms (integer)
        self.minCorpusCount = None # str


        # Maximum corpus frequency for terms (integer)
        self.maxCorpusCount = None # str


        # Minimum dictionary count (integer)
        self.minDictionaryCount = None # str


        # Maximum dictionary count (integer)
        self.maxDictionaryCount = None # str


        # Minimum word length (characters)
        self.minLength = None # str


        # Maximum word length (characters)
        self.maxLength = None # str


        # Attribute to sort by
        self.sortBy = None # str


        # Sort direction
        self.sortOrder = None # str


        # Maximum number of results to return
        self.limit = None # str

