#!/usr/bin/env python
"""
Copyright 2011 Wordnik, Inc.
 
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0
 
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

class WordsSearchInput:
    """

    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """

    def __init__(self):
        self.swaggerTypes = {
            'query': 'str',
            'caseSensitive': 'str',
            'includePartOfSpeech': 'str',
            'excludePartOfSpeech': 'str',
            'minCorpusCount': 'str',
            'maxCorpusCount': 'str',
            'minDictionaryCount': 'str',
            'maxDictionaryCount': 'str',
            'minLength': 'str',
            'maxLength': 'str',
            'skip': 'str',
            'limit': 'str'
        }



        # Search term
        self.query = None # str


        # Search case sensitive
        self.caseSensitive = None # str


        # Only include these comma-delimited parts of speech
        self.includePartOfSpeech = None # str


        # Exclude these comma-delimited parts of speech
        self.excludePartOfSpeech = None # str


        # Minimum corpus frequency for terms
        self.minCorpusCount = None # str


        # Maximum corpus frequency for terms
        self.maxCorpusCount = None # str


        # Minimum number of dictionary entries for words returned
        self.minDictionaryCount = None # str


        # Maximum dictionary definition count
        self.maxDictionaryCount = None # str


        # Minimum word length
        self.minLength = None # str


        # Maximum word length
        self.maxLength = None # str


        # Results to skip
        self.skip = None # str


        # Maximum number of results to return
        self.limit = None # str

